<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a458fe9d-7291-4eb2-ab1b-4c34c544533e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CarvedRock.Core\CarvedRock.Core.csproj" />
    <ProjectReference Include="..\CarvedRock.ServiceDefaults\CarvedRock.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.OpenAI" Version="13.4.6-preview.1.26319.6" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.13.0" />
    <!-- <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.5.1" /> -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="ModelContextProtocol" Version="1.4.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.15" />
  </ItemGroup>  

</Project>
